/*
 * File: app/view/dbfx.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.dbfx', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.dbfx',

    requires: [
        'MyApp.view.xcglpanelViewModel3',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.form.field.Display',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio'
    ],

    viewModel: {
        type: 'dbfx'
    },
    border: false,
    frame: true,
    height: 644,
    itemId: 'xcgl',
    width: 300,
    layout: 'accordion',
    bodyBorder: false,
    collapseDirection: 'left',
    collapsible: false,
    title: '对比分析',
    titleAlign: 'center',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'panel',
            layout: 'fit',
            title: '不同地区比较',
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'combobox',
                            margin: '10 0 10 0',
                            width: 234,
                            fieldLabel: '年度索引',
                            labelWidth: 60,
                            emptyText: '2008年'
                        },
                        {
                            xtype: 'combobox',
                            margin: '10 0 10 0',
                            fieldLabel: '核查来院',
                            labelWidth: 60,
                            emptyText: '全部'
                        },
                        {
                            xtype: 'combobox',
                            margin: '10 0 10 0',
                            fieldLabel: '地区索引',
                            labelWidth: 60,
                            emptyText: '辽宁省'
                        },
                        {
                            xtype: 'checkboxgroup',
                            margin: '10 0 10 0',
                            width: 186,
                            fieldLabel: 'Label',
                            hideLabel: true,
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    boxLabel: '违法用地'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    boxLabel: '实地伪变化'
                                }
                            ]
                        },
                        {
                            xtype: 'checkboxgroup',
                            margin: '10 0 10 0',
                            width: 186,
                            fieldLabel: 'Label',
                            hideLabel: true,
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    boxLabel: '违法用地'
                                }
                            ]
                        },
                        {
                            xtype: 'button',
                            margin: 10,
                            width: 90,
                            text: '确定'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            layout: 'fit',
            title: '同区类型比较',
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'combobox',
                            margin: '10 0 10 0',
                            fieldLabel: '年度索引',
                            labelWidth: 60,
                            emptyText: '2008年'
                        },
                        {
                            xtype: 'combobox',
                            margin: '10 0 10 0',
                            fieldLabel: '核查来源',
                            labelWidth: 60,
                            emptyText: '全部'
                        },
                        {
                            xtype: 'combobox',
                            margin: '10 0 10 0',
                            fieldLabel: '地区索引',
                            labelWidth: 60,
                            emptyText: '辽宁省'
                        },
                        {
                            xtype: 'button',
                            margin: 10,
                            width: 90,
                            text: '确定'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            layout: 'fit',
            title: '区域年度比较',
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'combobox',
                            margin: '10 0 10 0',
                            fieldLabel: '核查来源',
                            labelWidth: 60,
                            emptyText: '2008年'
                        },
                        {
                            xtype: 'container',
                            margin: '0 0 0 0',
                            width: 235,
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    value: '年度索引'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '10 0 10 0',
                            width: 234,
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'combobox',
                                    height: '',
                                    margin: '',
                                    width: 100,
                                    fieldLabel: '年度索引',
                                    hideLabel: true,
                                    labelWidth: 60,
                                    emptyText: '全部'
                                },
                                {
                                    xtype: 'displayfield',
                                    height: 20,
                                    margin: '0 5 0 5',
                                    fieldLabel: '至',
                                    hideLabel: true,
                                    labelAlign: 'top',
                                    value: '至'
                                },
                                {
                                    xtype: 'combobox',
                                    height: '',
                                    margin: '',
                                    width: 100,
                                    fieldLabel: '年度索引',
                                    hideLabel: true,
                                    labelWidth: 60,
                                    emptyText: '全部'
                                }
                            ]
                        },
                        {
                            xtype: 'combobox',
                            margin: '10 0 10 0',
                            fieldLabel: '地区索引',
                            labelWidth: 60,
                            emptyText: '辽宁省'
                        },
                        {
                            xtype: 'button',
                            margin: 20,
                            width: 90,
                            text: '确定'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            layout: 'fit',
            title: '图形对比分析',
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'radiogroup',
                            margin: '20 0 010 0',
                            width: 194,
                            fieldLabel: 'Label',
                            hideLabel: true,
                            items: [
                                {
                                    xtype: 'radiofield',
                                    name: 'duibiRadio',
                                    boxLabel: '两图对比',
                                    listeners: {
                                        change: 'onRadiofieldChange'
                                    }
                                },
                                {
                                    xtype: 'radiofield',
                                    name: 'duibiRadio',
                                    boxLabel: '四图对比'
                                }
                            ]
                        },
                        {
                            xtype: 'combobox',
                            id: 'graph1',
                            margin: '10 0 10 0',
                            fieldLabel: '第一幅图',
                            labelWidth: 60,
                            emptyText: '土地利用现状图'
                        },
                        {
                            xtype: 'combobox',
                            id: 'graph2',
                            margin: '10 0 10 0',
                            fieldLabel: '第二幅图',
                            labelWidth: 60,
                            emptyText: '土地利用规划图'
                        },
                        {
                            xtype: 'combobox',
                            id: 'graph3',
                            margin: '10 0 10 0',
                            fieldLabel: '第三幅图',
                            labelWidth: 60,
                            emptyText: '基本农田图'
                        },
                        {
                            xtype: 'combobox',
                            id: 'graph4',
                            margin: '10 0 10 0',
                            fieldLabel: '第四幅图',
                            labelWidth: 60,
                            emptyText: '建设用地审批图'
                        },
                        {
                            xtype: 'button',
                            margin: '10 0 0 0',
                            width: 90,
                            text: '确定'
                        }
                    ]
                }
            ]
        }
    ],

    onRadiofieldChange: function(field, newValue, oldValue, eOpts) {
        var graph3=Ext.getCmp("graph3");
        var graph4=Ext.getCmp("graph4");

             graph3.editable=newValue;
        graph4.editable=newValue;


    }

});