/*
 * File: app/view/dikuaifenxiWin.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.dikuaifenxiWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.dikuaifenxiwin',

    requires: [
        'MyApp.view.dikuaifenxiWinViewModel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.FieldSet',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.form.CheckboxGroup',
        'Ext.form.field.Checkbox',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.TextItem'
    ],

    viewModel: {
        type: 'dikuaifenxiwin'
    },
    frame: true,
    height: 422,
    width: 491,
    layout: 'fit',
    title: '地块分析',

    items: [
        {
            xtype: 'tabpanel',
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    height: 414,
                    title: '分析条件',
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'fieldset',
                            height: 174,
                            width: 421,
                            title: '分析地块',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    height: 108,
                                    header: false,
                                    title: 'My Grid Panel',
                                    forceFit: true,
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: '序号'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: 'X'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: 'Y'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    height: 33,
                                    margin: '',
                                    padding: '',
                                    width: 360,
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle',
                                        pack: 'center',
                                        padding: ''
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            width: 65,
                                            text: '选择'
                                        },
                                        {
                                            xtype: 'button',
                                            margin: '0 30 0 30',
                                            width: 65,
                                            text: '绘制'
                                        },
                                        {
                                            xtype: 'button',
                                            margin: '',
                                            width: 65,
                                            text: '导入'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            height: 117,
                            width: 421,
                            layout: 'absolute',
                            title: '叠加地图',
                            items: [
                                {
                                    xtype: 'checkboxgroup',
                                    x: 10,
                                    y: 0,
                                    height: 30,
                                    width: 421,
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            boxLabel: '土地利用现状'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            boxLabel: '土地供应'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            boxLabel: '土地规划'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'checkboxgroup',
                                    x: 10,
                                    y: 30,
                                    height: 30,
                                    width: 421,
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            boxLabel: '建设用地数据'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            boxLabel: '基本农田'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            boxLabel: '矿产资源规划'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'checkboxgroup',
                                    x: 10,
                                    y: 60,
                                    height: 30,
                                    width: 285,
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            boxLabel: '建设用地数据'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            boxLabel: '基本农田'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'button',
                                    x: 280,
                                    y: 65,
                                    text: '清除'
                                },
                                {
                                    xtype: 'button',
                                    x: 340,
                                    y: 65,
                                    text: '全选'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    margin: '0 10 0 10',
                                    width: 80,
                                    text: '分析'
                                },
                                {
                                    xtype: 'button',
                                    margin: '0 10 0 10',
                                    width: 80,
                                    text: '结果提取'
                                },
                                {
                                    xtype: 'button',
                                    margin: '0 10 0 10',
                                    width: 80,
                                    text: '导出结果'
                                },
                                {
                                    xtype: 'button',
                                    margin: '0 10 0 10',
                                    width: 80,
                                    text: '退出'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    title: '分析结果汇总'
                },
                {
                    xtype: 'panel',
                    title: '分析结果详细信息',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'tbtext',
                                    text: '土地利用现状'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});