/*
 * File: app/view/help.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.help', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.help',

    requires: [
        'MyApp.view.xcglpanelViewModel7',
        'Ext.menu.Menu',
        'Ext.menu.Item'
    ],

    viewModel: {
        type: 'help'
    },
    border: false,
    frame: true,
    height: 518,
    itemId: '',
    width: 208,
    layout: 'fit',
    bodyBorder: false,
    collapseDirection: 'left',
    collapsible: false,
    title: '帮助',
    titleAlign: 'center',

    items: [
        {
            xtype: 'menu',
            floating: false,
            width: 120,
            items: [
                {
                    xtype: 'menuitem',
                    text: '帮助文档'
                }
            ]
        }
    ]

});