/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'MyApp.view.MainViewViewModel',
        'MyApp.view.MainViewViewController',
        'Ext.Img',
        'Ext.button.Segmented',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.grid.View'
    ],

    controller: 'mainview',
    viewModel: {
        type: 'mainview'
    },
    html: '<div id="mapcontainer">hello world</div>',
    itemId: 'mainView',
    layout: 'border',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'panel',
            region: 'north',
            height: 72,
            html: '<h1 style="color:#333;;margin:25px 0px 0px 35px;">\n辽宁国土资源一张图管理平台</h1>',
            itemId: 'headerPanel',
            layout: 'absolute',
            title: '',
            items: [
                {
                    xtype: 'image',
                    x: 0,
                    y: 0,
                    height: '100%',
                    width: '100%',
                    src: 'resources/header-back.png'
                },
                {
                    xtype: 'image',
                    x: 1,
                    y: 1,
                    height: 72,
                    width: 400,
                    src: 'resources/header.png'
                },
                {
                    xtype: 'segmentedbutton',
                    x: 421,
                    y: 20,
                    height: 35,
                    margin: '',
                    width: 920,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            flex: 1,
                            margin: '0 1 0 1',
                            style: 'background-color:#57a2d8;\nborder:none;',
                            allowDepress: false,
                            enableToggle: true,
                            icon: '',
                            text: '巡查管理',
                            listeners: {
                                click: {
                                    fn: 'onButtonClick',
                                    scope: 'controller'
                                }
                            }
                        },
                        {
                            flex: 1,
                            margin: '',
                            style: 'background-color:#57a2d8;\nborder:none;',
                            text: '巡查导航',
                            listeners: {
                                click: {
                                    fn: 'onButtonClick1',
                                    scope: 'controller'
                                }
                            }
                        },
                        {
                            flex: 1,
                            margin: '0 1 0 1',
                            style: 'background-color:#57a2d8;\nborder:none;',
                            text: '执法网络',
                            listeners: {
                                click: 'onButtonClick2'
                            }
                        },
                        {
                            flex: 1,
                            margin: '',
                            style: 'background-color:#57a2d8;\nborder:none;',
                            text: '对比分析',
                            listeners: {
                                click: 'onButtonClick3'
                            }
                        },
                        {
                            flex: 1,
                            margin: '0 1 0 1',
                            style: 'background-color:#57a2d8;\nborder:none;',
                            width: 70,
                            text: '行政区',
                            listeners: {
                                click: 'onButtonClick5'
                            }
                        },
                        {
                            flex: 1,
                            margin: '',
                            style: 'background-color:#57a2d8;\nborder:none;',
                            text: '统计报表',
                            listeners: {
                                click: 'onButtonClick4'
                            }
                        },
                        {
                            flex: 1,
                            margin: '0 1 0 1',
                            style: 'background-color:#57a2d8;\nborder:none;',
                            text: '系统管理',
                            listeners: {
                                click: 'onButtonClick6'
                            }
                        },
                        {
                            flex: 1,
                            height: 25,
                            margin: '',
                            style: 'background-color:#57a2d8;\nborder:none;',
                            width: 70,
                            text: '帮助',
                            listeners: {
                                click: 'onButtonClick7'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'center',
            split: true,
            itemId: 'contentPanel',
            layout: 'border',
            closable: true,
            collapsible: true,
            header: false,
            title: 'Content',
            items: [
                {
                    xtype: 'tabpanel',
                    region: 'center',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            height: 469,
                            html: '<div id="mapContainer" style="height:100%"></div>',
                            id: '',
                            title: '地图',
                            tabConfig: {
                                xtype: 'tab',
                                closeText: '关闭'
                            }
                        },
                        {
                            xtype: 'panel',
                            closable: true,
                            title: 'Tab 2',
                            tabConfig: {
                                xtype: 'tab',
                                closeText: '关闭'
                            }
                        },
                        {
                            xtype: 'panel',
                            height: 413,
                            closable: true,
                            title: 'Tab 3'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    region: 'south',
                    split: true,
                    height: 144,
                    collapsible: true,
                    title: '信息',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'String'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'number',
                            text: 'Number'
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'date',
                            text: 'Date'
                        },
                        {
                            xtype: 'booleancolumn',
                            dataIndex: 'bool',
                            text: 'Boolean'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'west',
            split: true,
            id: 'menuContainer',
            width: 300,
            layout: 'fit',
            bodyBorder: false,
            bodyStyle: 'solid 2px #f00',
            collapseDirection: 'left',
            collapsible: true,
            header: false,
            title: ''
        }
    ],
    listeners: {
        afterrender: 'onMainViewAfterRender'
    },

    onButtonClick2: function(button, e, eOpts) {
        var container = Ext.getCmp('menuContainer');
             container.removeAll();
             var menu=new MyApp.view.zfwl();
             container.add(menu);
    },

    onButtonClick3: function(button, e, eOpts) {
        var container = Ext.getCmp('menuContainer');
             container.removeAll();
             var menu=new MyApp.view.dbfx();
             container.add(menu);
    },

    onButtonClick5: function(button, e, eOpts) {
        var container = Ext.getCmp('menuContainer');
             container.removeAll();
             var menu=new MyApp.view.xzq();
             container.add(menu);
    },

    onButtonClick4: function(button, e, eOpts) {
        var container = Ext.getCmp('menuContainer');
             container.removeAll();
             var menu=new MyApp.view.tjbb();
             container.add(menu);
    },

    onButtonClick6: function(button, e, eOpts) {
        var container = Ext.getCmp('menuContainer');
             container.removeAll();
             var menu=new MyApp.view.xtgl();
             container.add(menu);
    },

    onButtonClick7: function(button, e, eOpts) {
        var container = Ext.getCmp('menuContainer');
        container.removeAll();
        var menu=new MyApp.view.help();
        container.add(menu);
    },

    onMainViewAfterRender: function(component, eOpts) {
        var container = Ext.getCmp('menuContainer');
             container.removeAll();
             var menu=new MyApp.view.xcglpanel();
             container.add(menu);
    }

});