/*
 * File: app/view/tjbb.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.tjbb', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tjbb',

    requires: [
        'MyApp.view.xcglpanelViewModel4',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.Spinner',
        'Ext.form.field.Display'
    ],

    viewModel: {
        type: 'tjbb'
    },
    border: false,
    frame: true,
    height: 645,
    itemId: 'xcgl',
    width: 300,
    layout: 'accordion',
    bodyBorder: false,
    collapseDirection: 'left',
    collapsible: false,
    title: '统计报表',
    titleAlign: 'center',

    items: [
        {
            xtype: 'panel',
            layout: 'fit',
            title: '执法任务统计',
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'fieldset',
                            height: 103,
                            margin: '5 0 5 0',
                            title: '统计时间范围',
                            layout: {
                                type: 'vbox',
                                align: 'center'
                            },
                            items: [
                                {
                                    xtype: 'datefield',
                                    margin: '10 0 0 0',
                                    width: 200,
                                    fieldLabel: '从',
                                    labelWidth: 20
                                },
                                {
                                    xtype: 'datefield',
                                    margin: '10 0 0 0',
                                    width: 200,
                                    fieldLabel: '到',
                                    labelWidth: 20
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            height: 137,
                            margin: '10 0 10 0',
                            title: '行政区、单位、人员',
                            layout: {
                                type: 'vbox',
                                align: 'center'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    margin: '10 0 5 0',
                                    width: 241,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            boxLabel: '执法单位：'
                                        },
                                        {
                                            xtype: 'combobox',
                                            flex: 1,
                                            margin: '0 0 0 5',
                                            width: 191,
                                            fieldLabel: 'Label',
                                            hideLabel: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    margin: '5 0 5 0',
                                    width: 241,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            boxLabel: '执法单位：'
                                        },
                                        {
                                            xtype: 'combobox',
                                            flex: 1,
                                            margin: '0 0 0 5',
                                            width: 191,
                                            fieldLabel: 'Label',
                                            hideLabel: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    margin: '5 0 5 0',
                                    width: 241,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            boxLabel: '执法单位：'
                                        },
                                        {
                                            xtype: 'combobox',
                                            flex: 1,
                                            margin: '0 0 0 5',
                                            width: 112,
                                            fieldLabel: 'Label',
                                            hideLabel: true
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            height: 126,
                            margin: '5 0 5 0',
                            title: '其他条件',
                            layout: {
                                type: 'vbox',
                                align: 'center'
                            },
                            items: [
                                {
                                    xtype: 'checkboxgroup',
                                    height: 30,
                                    margin: '5 0 0 0',
                                    width: 234,
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            boxLabel: '超期'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            boxLabel: '未超期'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'checkboxgroup',
                                    height: 25,
                                    margin: '5 0 0 0',
                                    width: 234,
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            boxLabel: '已完成'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            boxLabel: '未完成'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'checkboxgroup',
                                    height: 23,
                                    margin: '5 0 0 0',
                                    width: 234,
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            boxLabel: '发现可疑地块'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            boxLabel: '未发现可疑地块'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'button',
                            margin: '10 90 0 90',
                            width: 278,
                            text: '查询'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            layout: 'fit',
            title: '巡查轨迹统计',
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'fieldset',
                            height: 103,
                            margin: '5 0 5 0',
                            title: '统计时间范围',
                            layout: {
                                type: 'vbox',
                                align: 'center'
                            },
                            items: [
                                {
                                    xtype: 'datefield',
                                    margin: '10 0 0 0',
                                    width: 200,
                                    fieldLabel: '从',
                                    labelWidth: 20
                                },
                                {
                                    xtype: 'datefield',
                                    margin: '10 0 0 0',
                                    width: 200,
                                    fieldLabel: '到',
                                    labelWidth: 20
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            height: 137,
                            margin: '10 0 10 0',
                            title: '行政区、单位、人员',
                            layout: {
                                type: 'vbox',
                                align: 'center'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    margin: '10 0 5 0',
                                    width: 241,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            boxLabel: '执法单位：'
                                        },
                                        {
                                            xtype: 'combobox',
                                            flex: 1,
                                            margin: '0 0 0 5',
                                            width: 191,
                                            fieldLabel: 'Label',
                                            hideLabel: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    margin: '5 0 5 0',
                                    width: 241,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            boxLabel: '执法单位：'
                                        },
                                        {
                                            xtype: 'combobox',
                                            flex: 1,
                                            margin: '0 0 0 5',
                                            width: 191,
                                            fieldLabel: 'Label',
                                            hideLabel: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    margin: '5 0 5 0',
                                    width: 241,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            boxLabel: '执法单位：'
                                        },
                                        {
                                            xtype: 'combobox',
                                            flex: 1,
                                            margin: '0 0 0 5',
                                            width: 112,
                                            fieldLabel: 'Label',
                                            hideLabel: true
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            height: 96,
                            margin: '5 0 5 0',
                            title: '其他条件',
                            layout: {
                                type: 'vbox',
                                align: 'center'
                            },
                            items: [
                                {
                                    xtype: 'radiogroup',
                                    height: 34,
                                    width: 235,
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: '按行政区分析'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: '按巡查轨迹分析'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'checkboxgroup',
                                    height: 23,
                                    margin: 0,
                                    width: 234,
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            boxLabel: '发现可疑地块'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            boxLabel: '未发现可疑地块'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'button',
                            margin: '10 90 0 90',
                            width: 278,
                            text: '查询'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            layout: 'fit',
            title: '巡查超期统计',
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'fieldset',
                            height: 103,
                            margin: '5 0 5 0',
                            title: '统计时间范围',
                            layout: {
                                type: 'vbox',
                                align: 'center'
                            },
                            items: [
                                {
                                    xtype: 'datefield',
                                    margin: '10 0 0 0',
                                    width: 200,
                                    fieldLabel: '从',
                                    labelWidth: 20
                                },
                                {
                                    xtype: 'datefield',
                                    margin: '10 0 0 0',
                                    width: 200,
                                    fieldLabel: '到',
                                    labelWidth: 20
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            height: 137,
                            margin: '10 0 10 0',
                            title: '行政区、单位、人员',
                            layout: {
                                type: 'vbox',
                                align: 'center'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    margin: '10 0 5 0',
                                    width: 241,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            boxLabel: '执法单位：'
                                        },
                                        {
                                            xtype: 'combobox',
                                            flex: 1,
                                            margin: '0 0 0 5',
                                            width: 191,
                                            fieldLabel: 'Label',
                                            hideLabel: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    margin: '5 0 5 0',
                                    width: 241,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            boxLabel: '执法单位：'
                                        },
                                        {
                                            xtype: 'combobox',
                                            flex: 1,
                                            margin: '0 0 0 5',
                                            width: 191,
                                            fieldLabel: 'Label',
                                            hideLabel: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    margin: '5 0 5 0',
                                    width: 241,
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            boxLabel: '执法单位：'
                                        },
                                        {
                                            xtype: 'combobox',
                                            flex: 1,
                                            margin: '0 0 0 5',
                                            width: 112,
                                            fieldLabel: 'Label',
                                            hideLabel: true
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            height: 96,
                            margin: '5 0 5 0',
                            title: '其他条件',
                            layout: {
                                type: 'vbox',
                                align: 'center'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    flex: 0,
                                    margin: '10 0 0 0',
                                    width: 236,
                                    header: false,
                                    title: 'My Panel',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'spinnerfield',
                                            height: 25,
                                            margin: '',
                                            maxHeight: 25,
                                            width: 79,
                                            fieldLabel: '超过',
                                            labelWidth: 30
                                        },
                                        {
                                            xtype: 'displayfield',
                                            margin: '0 0 0 5',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            value: ' 天未巡查'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'checkboxgroup',
                                    height: 23,
                                    margin: 0,
                                    width: 243,
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            boxLabel: '当前超期'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            boxLabel: '历史超期'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'button',
                            margin: '10 90 0 90',
                            width: 278,
                            text: '查询'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            layout: 'fit',
            title: '核查报表统计',
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'combobox',
                            margin: '15 0 5 0',
                            fieldLabel: '年度索引',
                            labelWidth: 60
                        },
                        {
                            xtype: 'combobox',
                            margin: '5 0 5 0',
                            fieldLabel: '核查来源',
                            labelWidth: 60
                        },
                        {
                            xtype: 'combobox',
                            margin: '5 0 5 0',
                            fieldLabel: '行政区',
                            labelWidth: 60
                        },
                        {
                            xtype: 'combobox',
                            margin: '5 0 5 0',
                            fieldLabel: '统计报表',
                            labelWidth: 60
                        },
                        {
                            xtype: 'container',
                            margin: '20 0  0 0',
                            width: 200,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    margin: '0 30 0 0',
                                    text: '确定'
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    text: '重新计算'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});