/*
 * File: app/view/tudihechaWin.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.tudihechaWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.tudihechawin',

    requires: [
        'MyApp.view.tudihechaWinViewModel',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.form.field.Display',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'tudihechawin'
    },
    height: 596,
    width: 627,
    layout: 'fit',
    title: '土地属性核查',

    items: [
        {
            xtype: 'form',
            layout: 'border',
            bodyPadding: 10,
            header: false,
            title: 'My Form',
            items: [
                {
                    xtype: 'container',
                    region: 'west',
                    width: 284,
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: '行政区代码',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '县区名',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '乡镇名称',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '前时相',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '后时相',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'X坐标',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Y坐标',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '检测编号',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '检测面积',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '备注',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '地块编号',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '地块分类',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '地块面积',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '耕地面积',
                            labelWidth: 70
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: '农用地面积',
                            labelWidth: 70
                        }
                    ]
                },
                {
                    xtype: 'container',
                    region: 'east',
                    width: 318,
                    layout: 'vbox',
                    items: [
                        {
                            xtype: 'textfield',
                            width: 259,
                            fieldLabel: '基本农田面积',
                            labelWidth: 85
                        },
                        {
                            xtype: 'textfield',
                            width: 259,
                            fieldLabel: '未利用地面积',
                            labelWidth: 85
                        },
                        {
                            xtype: 'textfield',
                            width: 259,
                            fieldLabel: '实际用途',
                            labelWidth: 85
                        },
                        {
                            xtype: 'textfield',
                            width: 259,
                            fieldLabel: '用地单位',
                            labelWidth: 85
                        },
                        {
                            xtype: 'textfield',
                            width: 259,
                            fieldLabel: '项目类型',
                            labelWidth: 85
                        },
                        {
                            xtype: 'textfield',
                            width: 259,
                            fieldLabel: '合法性审查',
                            labelWidth: 85
                        },
                        {
                            xtype: 'textfield',
                            width: 259,
                            fieldLabel: '违法类型',
                            labelWidth: 85
                        },
                        {
                            xtype: 'fieldset',
                            height: 236,
                            width: 269,
                            layout: 'absolute',
                            title: '上传资料',
                            items: [
                                {
                                    xtype: 'textfield',
                                    x: 0,
                                    y: 10,
                                    width: 120,
                                    fieldLabel: '拍摄人',
                                    labelWidth: 50
                                },
                                {
                                    xtype: 'datefield',
                                    x: 130,
                                    y: 10,
                                    width: 113,
                                    fieldLabel: '时间',
                                    labelWidth: 30
                                },
                                {
                                    xtype: 'textfield',
                                    x: 0,
                                    y: 40,
                                    width: 245,
                                    fieldLabel: '单位',
                                    labelWidth: 30
                                },
                                {
                                    xtype: 'textfield',
                                    x: 0,
                                    y: 70,
                                    width: 245,
                                    fieldLabel: '说明',
                                    labelWidth: 30
                                },
                                {
                                    xtype: 'displayfield',
                                    x: 0,
                                    y: 100,
                                    width: 30,
                                    fieldLabel: '',
                                    value: '照片视频'
                                },
                                {
                                    xtype: 'gridpanel',
                                    x: 35,
                                    y: 101,
                                    autoScroll: true,
                                    height: 80,
                                    header: false,
                                    title: 'My Grid Panel',
                                    forceFit: true,
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            width: 57,
                                            dataIndex: 'string',
                                            text: '序号'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'string',
                                            text: '文件名'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'button',
                                    x: 70,
                                    y: 185,
                                    width: 60,
                                    text: '添加'
                                },
                                {
                                    xtype: 'button',
                                    x: 150,
                                    y: 185,
                                    width: 60,
                                    text: '删除'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'south',
                    height: 74,
                    header: false,
                    title: 'My Panel',
                    layout: {
                        type: 'hbox',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            margin: '0 80 0 0',
                            width: 85,
                            text: '保存'
                        },
                        {
                            xtype: 'button',
                            margin: '',
                            width: 85,
                            text: '关闭'
                        }
                    ]
                }
            ]
        }
    ]

});