/*
 * File: app/view/xcglpanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.xcglpanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.xcglpanel',

    onComboboxSelect: function(combo, records, eOpts) {
        //行政区选择之后
    },

    onZfdwidSelect: function(combo, records, eOpts) {
        var dm=records[0].data.dm;
        var zhifarenyuan=Ext.getCmp("zhifarenyuan");
        //zhifarenyuan.store;

        //执法单位选择之后

        //     var store = new Ext.data.ArrayStore({
        //             fields: [
        //                 {
        //                     name: 'name'
        //                 }
        //             ],
        //             proxy: {
        //                 type: 'ajax',
        //                 url: 'getQhArray',
        //                 reader: {
        //                     type: 'json'
        //                 }
        //             }});

        // zhifarenyuan.store=store;
        // zhifarenyuan.displayField='name';
        // store.load();

    }

});
