/*
 * File: app/view/xcglpanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.xcglpanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.xcglpanel',

    requires: [
        'MyApp.view.xcglpanelViewModel',
        'MyApp.view.xcglpanelViewController',
        'Ext.form.Panel',
        'Ext.form.field.Date',
        'Ext.button.Split',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Date',
        'Ext.form.field.Checkbox',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Spinner',
        'Ext.form.Label',
        'Ext.button.Segmented',
        'Ext.grid.column.Number',
        'Ext.form.FieldSet',
        'Ext.form.field.Display',
        'Ext.form.field.TextArea'
    ],

    controller: 'xcglpanel',
    viewModel: {
        type: 'xcglpanel'
    },
    border: false,
    frame: true,
    height: 743,
    itemId: 'xcgl',
    width: 317,
    layout: 'accordion',
    bodyBorder: false,
    collapseDirection: 'left',
    collapsible: false,
    title: '巡查管理',
    titleAlign: 'center',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'panel',
            layout: 'border',
            title: '巡查轨迹',
            items: [
                {
                    xtype: 'form',
                    region: 'north',
                    height: 128,
                    id: 'guiJIForm',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    method: 'get',
                    standardSubmit: false,
                    url: 'getGuiJi',
                    waitTitle: '查询中',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'datefield',
                            id: 'guijiStart',
                            fieldLabel: '起始时间',
                            labelWidth: 60,
                            name: 'startTime',
                            allowBlank: false
                        },
                        {
                            xtype: 'datefield',
                            id: 'guijiEnd',
                            fieldLabel: '终止时间',
                            labelWidth: 60,
                            name: 'endTime',
                            allowBlank: false
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            margins: '',
                            height: 84,
                            margin: '',
                            width: 311,
                            header: false,
                            title: 'My Panel',
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'guijiBtn',
                                    margin: '0 10 0 0',
                                    width: 80,
                                    allowDepress: false,
                                    text: '轨迹查询',
                                    listeners: {
                                        click: 'onButtonClick'
                                    }
                                },
                                {
                                    xtype: 'splitbutton',
                                    flex: 1,
                                    maxWidth: 90,
                                    width: 80,
                                    text: '轨迹回放',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                text: '8000'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: '1'
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    region: 'center',
                    id: 'guiJIPanel',
                    header: false,
                    title: 'My Grid Panel',
                    forceFit: true,
                    store: 'guiJIResult',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 90,
                            defaultWidth: 90,
                            align: 'center',
                            dataIndex: 'guijihao',
                            text: '轨迹编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 90,
                            defaultWidth: 90,
                            align: 'center',
                            dataIndex: 'renwuhao',
                            text: '任务编号'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 90,
                            defaultWidth: 90,
                            align: 'center',
                            dataIndex: 'time',
                            formatter: '',
                            text: '时间'
                        }
                    ],
                    viewConfig: {
                        getRowClass: function(record, rowIndex, rowParams, store) {
                            return "little_font";
                        },
                        enableTextSelection: true
                    }
                }
            ]
        },
        {
            xtype: 'panel',
            title: '巡查监控',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 4,
                    title: '当前在线人员：',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 60,
                            dataIndex: 'string',
                            text: '序号'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 60,
                            dataIndex: 'string',
                            text: '姓名'
                        },
                        {
                            xtype: 'datecolumn',
                            width: 74,
                            dataIndex: 'date',
                            text: '连线时间',
                            format: 'Y-m-d'
                        },
                        {
                            xtype: 'datecolumn',
                            width: 90,
                            dataIndex: 'date',
                            text: 'Date'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    height: 50,
                    header: false,
                    title: 'My Panel',
                    layout: {
                        type: 'hbox',
                        align: 'middle'
                    },
                    items: [
                        {
                            xtype: 'button',
                            flex: 1,
                            margin: '0 10 0 10',
                            text: '在线人员'
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            margin: '0 10 0 10',
                            text: '开始监控'
                        },
                        {
                            xtype: 'button',
                            flex: 1,
                            margin: '0 10 0 10',
                            text: '取消监控'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            layout: 'fit',
            title: '巡查超期告警',
            items: [
                {
                    xtype: 'form',
                    autoScroll: true,
                    layout: 'absolute',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    items: [
                        {
                            xtype: 'checkboxfield',
                            x: 10,
                            y: 60,
                            width: 80,
                            fieldLabel: 'Label',
                            hideLabel: true,
                            boxLabel: '执法单位'
                        },
                        {
                            xtype: 'combobox',
                            x: 10,
                            y: 20,
                            width: 260,
                            fieldLabel: '行政区选择',
                            labelWidth: 75,
                            displayField: 'name',
                            store: 'xingzhengqu',
                            listeners: {
                                select: {
                                    fn: 'onComboboxSelect',
                                    scope: 'controller'
                                }
                            }
                        },
                        {
                            xtype: 'checkboxfield',
                            x: 10,
                            y: 100,
                            width: 80,
                            fieldLabel: 'Label',
                            hideLabel: true,
                            boxLabel: '执法人员'
                        },
                        {
                            xtype: 'combobox',
                            x: 90,
                            y: 60,
                            id: 'zfdwid',
                            width: 180,
                            fieldLabel: 'Label',
                            hideLabel: true,
                            displayField: 'name',
                            store: 'zfdwStore',
                            listeners: {
                                select: {
                                    fn: 'onZfdwidSelect',
                                    scope: 'controller'
                                }
                            }
                        },
                        {
                            xtype: 'combobox',
                            x: 90,
                            y: 100,
                            id: 'zhifarenyuan',
                            width: 180,
                            fieldLabel: 'Label',
                            hideLabel: true,
                            displayField: 'name',
                            store: 'zfryStore'
                        },
                        {
                            xtype: 'spinnerfield',
                            x: 14,
                            y: 147,
                            height: 25,
                            margin: '',
                            maxHeight: 25,
                            width: 120,
                            fieldLabel: '调查时限',
                            labelWidth: 60
                        },
                        {
                            xtype: 'label',
                            x: 138,
                            y: 150,
                            height: 20,
                            text: '天未巡查'
                        },
                        {
                            xtype: 'button',
                            x: 112,
                            y: 191,
                            width: 70,
                            text: '查询'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            title: '任务状态',
            layout: {
                type: 'vbox',
                align: 'stretch',
                pack: 'center',
                padding: '3 15 0 15'
            },
            items: [
                {
                    xtype: 'segmentedbutton',
                    flex: 0,
                    height: 35,
                    padding: 2,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            flex: 1,
                            text: '未完成'
                        },
                        {
                            flex: 1,
                            text: '未下达'
                        },
                        {
                            flex: 1,
                            text: '已完成'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    header: false,
                    title: 'My Grid Panel',
                    forceFit: true,
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'number',
                            text: '序号'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: '任务编号'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            frame: true,
            layout: 'fit',
            bodyBorder: true,
            title: '任务下达',
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'fieldset',
                            autoScroll: true,
                            height: 320,
                            margin: '0 5 5 5',
                            title: '任务信息',
                            layout: {
                                type: 'vbox',
                                align: 'center',
                                padding: '10 0 0 0'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    margin: '',
                                    fieldLabel: '任务编号',
                                    labelWidth: 60
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '10 0 0 0',
                                    fieldLabel: '行政区',
                                    labelWidth: 60,
                                    emptyText: '辽宁省'
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '10 0 0 0',
                                    fieldLabel: '执法单位',
                                    labelWidth: 60,
                                    emptyText: '辽宁省国土资源行政执法'
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '10 0 0 0',
                                    fieldLabel: '执法人员',
                                    labelWidth: 60,
                                    emptyText: '刘峰'
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '10 0 0 0',
                                    fieldLabel: '接手号码',
                                    labelWidth: 60,
                                    emptyText: '13898890734'
                                },
                                {
                                    xtype: 'panel',
                                    flex: 0,
                                    margin: '10 0 0 0',
                                    width: 236,
                                    header: false,
                                    title: 'My Panel',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'spinnerfield',
                                            height: 25,
                                            margin: '',
                                            maxHeight: 25,
                                            width: 120,
                                            fieldLabel: '调查时限',
                                            labelWidth: 60
                                        },
                                        {
                                            xtype: 'displayfield',
                                            margin: '0 0 0 5',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            value: ' 天'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'textareafield',
                                    margin: '10 0 0 0',
                                    fieldLabel: '任务描述',
                                    labelWidth: 60,
                                    emptyText: '是否占用耕地'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            flex: 1,
                            title: '地块信息',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'panel',
                                    flex: 0,
                                    height: 35,
                                    header: false,
                                    title: 'My Panel',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            margin: '5 10 5 10',
                                            text: '选择'
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            margin: '5 10 5 10',
                                            text: '绘制'
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            margin: '5 10 5 10',
                                            text: '导入'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    width: 271,
                                    header: false,
                                    title: 'My Grid Panel',
                                    forceFit: true,
                                    columns: [
                                        {
                                            xtype: 'numbercolumn',
                                            width: 70,
                                            sortable: false,
                                            align: 'center',
                                            dataIndex: 'number',
                                            text: '序号'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            height: 20,
                                            width: 89,
                                            align: 'center',
                                            dataIndex: 'number',
                                            text: 'X'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            height: 20,
                                            width: 90,
                                            align: 'center',
                                            dataIndex: 'number',
                                            text: 'Y'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 0,
                            height: 35,
                            header: false,
                            title: 'My Panel',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    margin: 5,
                                    text: '新建任务'
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    margin: 5,
                                    text: '保存任务'
                                },
                                {
                                    xtype: 'button',
                                    flex: 1.5,
                                    margin: 5,
                                    text: '短信发送任务'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            frame: true,
            bodyBorder: true,
            title: '巡查结果',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    width: 271,
                    header: false,
                    title: 'My Grid Panel',
                    forceFit: true,
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            width: 70,
                            sortable: false,
                            align: 'center',
                            dataIndex: 'number',
                            text: '标识'
                        },
                        {
                            xtype: 'numbercolumn',
                            height: 20,
                            width: 89,
                            align: 'center',
                            dataIndex: 'number',
                            text: '任务编号'
                        },
                        {
                            xtype: 'numbercolumn',
                            height: 20,
                            width: 90,
                            align: 'center',
                            dataIndex: 'number',
                            text: 'Y'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'panel',
                            flex: 0,
                            height: 35,
                            header: false,
                            title: 'My Panel',
                            layout: {
                                type: 'hbox',
                                align: 'middle'
                            },
                            items: [
                                {
                                    xtype: 'datefield',
                                    flex: 1,
                                    margin: '0 5 0 0',
                                    width: 293,
                                    fieldLabel: '从',
                                    labelWidth: 20
                                },
                                {
                                    xtype: 'datefield',
                                    flex: 1,
                                    margin: '0 0 0 5',
                                    width: 293,
                                    fieldLabel: '到',
                                    labelWidth: 20
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 0,
                            height: 35,
                            header: false,
                            title: 'My Panel',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    margin: '5 10 5 10',
                                    text: '全部'
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    margin: '5 10 5 10',
                                    text: '搜索'
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    margin: '5 10 5 10',
                                    text: '定位'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],

    onButtonClick: function(button, e, eOpts) {
        var start = Ext.getCmp('guijiStart');
        var end = Ext.getCmp('guijiStart');
        var guiJIForm=Ext.getCmp('guiJIForm');
        guiJIForm.form.submit({
            success:function(f,a){
            var panel=Ext.getCmp('guiJIPanel');
            var resultArray=a.result.info;
            panel.store.loadData(resultArray,false);
            },
            failure:function(f,a){

                if(a.failureType=="client"){return;}else{alert("获取数据失败！");}
            }



        });



    }

});