/*
 * File: app/view/xtgl.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.xtgl', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.xtgl',

    requires: [
        'MyApp.view.xcglpanelViewModel6',
        'Ext.form.Panel',
        'Ext.form.field.File',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.selection.CheckboxModel',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.Label',
        'Ext.form.field.ComboBox'
    ],

    viewModel: {
        type: 'xtgl'
    },
    border: false,
    frame: true,
    height: 616,
    itemId: 'xcgl',
    width: 300,
    layout: 'accordion',
    bodyBorder: false,
    collapseDirection: 'left',
    collapsible: false,
    title: '系统管理',
    titleAlign: 'center',

    items: [
        {
            xtype: 'panel',
            layout: 'fit',
            title: '数据导入',
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'filefield',
                            margin: '10 0 0 0',
                            width: 200,
                            fieldLabel: 'Label',
                            hideLabel: true,
                            emptyText: '选择导入数据所在文件夹',
                            buttonText: '浏览'
                        },
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            height: 221,
                            margin: '10 0 0 0',
                            header: false,
                            title: 'My Grid Panel',
                            forceFit: true,
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: '文件信息'
                                }
                            ],
                            selModel: {
                                selType: 'checkboxmodel'
                            }
                        },
                        {
                            xtype: 'button',
                            margin: '10 90 10 90',
                            text: '接收'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            layout: 'fit',
            title: '数据导出',
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'fieldset',
                            height: 149,
                            margin: '5 0 5 0',
                            width: 278,
                            title: '时间范围',
                            layout: {
                                type: 'vbox',
                                align: 'center'
                            },
                            items: [
                                {
                                    xtype: 'datefield',
                                    margin: '10 0 0 0',
                                    width: 200,
                                    fieldLabel: '从',
                                    labelWidth: 20
                                },
                                {
                                    xtype: 'datefield',
                                    margin: '10 0 0 0',
                                    width: 200,
                                    fieldLabel: '到',
                                    labelWidth: 20
                                },
                                {
                                    xtype: 'container',
                                    height: 56,
                                    width: 182,
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            margin: '0 30 0 0 ',
                                            width: 73,
                                            text: '查询'
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            margin: '',
                                            width: 77,
                                            text: '导出'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'tabpanel',
                            flex: 1,
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: '调查轨迹'
                                },
                                {
                                    xtype: 'panel',
                                    title: '调查地块'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            layout: 'fit',
            title: '用户管理',
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            height: 73,
                            width: 255,
                            layout: {
                                type: 'vbox',
                                align: 'stretch',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'label',
                                    text: '用户所属行政区：'
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '7 0 0 0',
                                    width: 251,
                                    fieldLabel: '用户所属行政区',
                                    hideLabel: true,
                                    labelWidth: 70
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 73,
                            width: 255,
                            layout: {
                                type: 'vbox',
                                align: 'stretch',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'label',
                                    text: '用户所属单位：'
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '7 0 0 0',
                                    width: 251,
                                    fieldLabel: '用户所属行政区',
                                    hideLabel: true,
                                    labelWidth: 70
                                }
                            ]
                        },
                        {
                            xtype: 'button',
                            margin: '20 90 0 90',
                            text: '查询'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            layout: 'fit',
            title: '用户密码修改',
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'container',
                            height: 176,
                            width: 230,
                            layout: {
                                type: 'vbox',
                                align: 'stretch',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    width: 278,
                                    fieldLabel: '用户名',
                                    labelWidth: 60
                                },
                                {
                                    xtype: 'textfield',
                                    margins: '',
                                    margin: '5 0 0 0',
                                    fieldLabel: '原密码',
                                    labelWidth: 60
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '10 0 0 0',
                                    fieldLabel: '新密码',
                                    labelWidth: 60
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '10 0 0 0',
                                    fieldLabel: '新密码',
                                    labelWidth: 60
                                }
                            ]
                        },
                        {
                            xtype: 'button',
                            margin: '0 90 0 90',
                            width: 86,
                            text: '查询'
                        }
                    ]
                }
            ]
        }
    ]

});