/*
 * File: app/view/xzq.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.xzq', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.xzq',

    requires: [
        'MyApp.view.xcglpanelViewModel5'
    ],

    viewModel: {
        type: 'xzq'
    },
    border: false,
    frame: true,
    height: 629,
    itemId: 'xcgl',
    width: 300,
    layout: 'accordion',
    bodyBorder: false,
    collapseDirection: 'left',
    collapsible: false,
    title: '行政区',
    titleAlign: 'center'

});