/*
 * File: app/view/zfwl.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.zfwl', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.zfwl',

    requires: [
        'MyApp.view.xcglpanelViewModel2',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio'
    ],

    viewModel: {
        type: 'zfwl'
    },
    border: false,
    frame: true,
    height: 619,
    itemId: 'xcgl',
    width: 300,
    layout: 'accordion',
    bodyBorder: false,
    collapseDirection: 'left',
    collapsible: false,
    title: '执法网络',
    titleAlign: 'center',

    items: [
        {
            xtype: 'panel',
            layout: 'fit',
            title: '网络查询',
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'fieldset',
                            height: 136,
                            width: 282,
                            title: '根据行政区查询',
                            layout: {
                                type: 'vbox',
                                align: 'center'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    margin: '10 0 0 0',
                                    width: 186,
                                    fieldLabel: '行政区',
                                    labelWidth: 50
                                },
                                {
                                    xtype: 'checkboxfield',
                                    margin: '10 0 0 0',
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    boxLabel: '包含下级行政区'
                                },
                                {
                                    xtype: 'button',
                                    margin: '10 0 0 0',
                                    width: 70,
                                    text: '确定'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            height: 156,
                            width: 282,
                            title: '根据人员查询',
                            layout: {
                                type: 'vbox',
                                align: 'center'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    margin: '10 0 0 0',
                                    width: 186,
                                    fieldLabel: '人员姓名',
                                    labelWidth: 60
                                },
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'radiogroup',
                                            margin: '20 0 0 0',
                                            width: 180,
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            items: [
                                                {
                                                    xtype: 'radiofield',
                                                    name: 'queryCondition',
                                                    boxLabel: '模糊查询'
                                                },
                                                {
                                                    xtype: 'radiofield',
                                                    name: 'queryCondition',
                                                    boxLabel: '精确查询'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'button',
                                    margin: '10 0 0 0',
                                    width: 70,
                                    text: '确定'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            title: '历史网络查询',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'fieldset',
                    height: 136,
                    margin: 10,
                    width: 282,
                    title: '根据行政区查询',
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'combobox',
                            margin: '10 0 0 0',
                            width: 186,
                            fieldLabel: '行政区',
                            labelWidth: 50
                        },
                        {
                            xtype: 'checkboxfield',
                            margin: '10 0 0 0',
                            fieldLabel: 'Label',
                            hideLabel: true,
                            boxLabel: '包含下级行政区'
                        },
                        {
                            xtype: 'button',
                            margin: '10 0 0 0',
                            width: 70,
                            text: '确定'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    height: 118,
                    margin: 10,
                    width: 282,
                    title: '根据人员查询',
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'combobox',
                            margin: '10 0 0 0',
                            width: 186,
                            fieldLabel: '人员姓名',
                            labelWidth: 60
                        },
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'center'
                            }
                        },
                        {
                            xtype: 'button',
                            margin: '20 0 0 0',
                            width: 70,
                            text: '确定'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            layout: 'fit',
            title: '执法单位管理',
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    layout: {
                        type: 'vbox',
                        align: 'center'
                    },
                    items: [
                        {
                            xtype: 'combobox',
                            margin: 20,
                            width: 190,
                            fieldLabel: '所属行政区',
                            labelWidth: 70
                        },
                        {
                            xtype: 'combobox',
                            margin: 0,
                            width: 190,
                            fieldLabel: '执法单位',
                            labelWidth: 70
                        },
                        {
                            xtype: 'container',
                            margin: 20,
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    margin: '0 20',
                                    width: 70,
                                    text: '查询'
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    width: 70,
                                    text: '查询'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            layout: 'fit',
            title: '执法人员管理',
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'combobox',
                            margin: '10 0 5 0',
                            width: 220,
                            fieldLabel: '所属行政区',
                            labelWidth: 83
                        },
                        {
                            xtype: 'container',
                            margin: '5 0 5 0',
                            width: 280,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    boxLabel: '执法人员：'
                                },
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    margin: '0 0 0 5',
                                    width: 134,
                                    fieldLabel: 'Label',
                                    hideLabel: true
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '5 0 5 0',
                            width: 280,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    boxLabel: '上岗证号：'
                                },
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    margin: '0 0 0 5',
                                    width: 134,
                                    fieldLabel: 'Label',
                                    hideLabel: true
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '5 0 5 0',
                            width: 280,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    boxLabel: '移动手机：'
                                },
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    margin: '0 0 0 5',
                                    width: 134,
                                    fieldLabel: 'Label',
                                    hideLabel: true
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '5 0 5 0',
                            width: 280,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    boxLabel: '办公电哈：'
                                },
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    margin: '0 0 0 5',
                                    width: 134,
                                    fieldLabel: 'Label',
                                    hideLabel: true
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '5 0 5 0',
                            width: 280,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    boxLabel: '内部小号：'
                                },
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    margin: '0 0 0 5',
                                    width: 134,
                                    fieldLabel: 'Label',
                                    hideLabel: true
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '20 0 5 0',
                            width: 280,
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    margin: '0 20 0 0',
                                    width: 70,
                                    text: '查询'
                                },
                                {
                                    xtype: 'button',
                                    margin: '0 20 0 0',
                                    width: 70,
                                    text: '编辑'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            frame: true,
            layout: 'fit',
            bodyBorder: true,
            title: '执法网络管理',
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            margin: '5 0 5 0',
                            width: 280,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    boxLabel: '地区'
                                },
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    margin: '0 0 0 5',
                                    width: 134,
                                    fieldLabel: 'Label',
                                    hideLabel: true
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '5 0 5 0',
                            width: 280,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    boxLabel: '区县'
                                },
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    margin: '0 0 0 5',
                                    width: 134,
                                    fieldLabel: 'Label',
                                    hideLabel: true
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '5 0 5 0',
                            width: 280,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    boxLabel: '乡镇'
                                },
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    margin: '0 0 0 5',
                                    width: 134,
                                    fieldLabel: 'Label',
                                    hideLabel: true
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '5 0 5 0',
                            width: 280,
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    boxLabel: '村庄'
                                },
                                {
                                    xtype: 'combobox',
                                    flex: 1,
                                    margin: '0 0 0 5',
                                    width: 134,
                                    fieldLabel: 'Label',
                                    hideLabel: true
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '5 0 5 0',
                            width: 280,
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    fieldLabel: 'Label',
                                    hideLabel: true,
                                    boxLabel: '已指定负责人'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '20 0 5 0',
                            width: 280,
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    margin: '0 20 0 0',
                                    width: 70,
                                    text: '查询'
                                },
                                {
                                    xtype: 'button',
                                    margin: '0 20 0 0',
                                    width: 70,
                                    text: '编辑'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});