package cn.edu.bnu.land.domain;

// Generated 2015-1-27 8:44:40 by Hibernate Tools 3.4.0.CR1

/**
 * Dcgj generated by hbm2java
 */
public class Dcgj implements java.io.Serializable {

	private DcgjId id;

	public Dcgj() {
	}

	public Dcgj(DcgjId id) {
		this.id = id;
	}

	public DcgjId getId() {
		return this.id;
	}

	public void setId(DcgjId id) {
		this.id = id;
	}

}
