package cn.edu.bnu.land.domain;

import javax.persistence.Column;


// Generated 2015-1-26 20:13:39 by Hibernate Tools 3.4.0.CR1

/**
 * Xzqh generated by hbm2java
 */

public class Xzqh implements java.io.Serializable {

	private int id;
	private String xzqm;
	private String qhdm;

	public Xzqh() {
	}

	public Xzqh(int id, String xzqm, String qhdm) {
		this.id = id;
		this.xzqm = xzqm;
		this.qhdm = qhdm;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getXzqm() {
		return this.xzqm;
	}

	public void setXzqm(String xzqm) {
		this.xzqm = xzqm;
	}

	public String getQhdm() {
		return this.qhdm;
	}

	public void setQhdm(String qhdm) {
		this.qhdm = qhdm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Xzqh))
			return false;
		Xzqh castOther = (Xzqh) other;

		return (this.getId() == castOther.getId())
				&& ((this.getXzqm() == castOther.getXzqm()) || (this.getXzqm() != null
						&& castOther.getXzqm() != null && this.getXzqm()
						.equals(castOther.getXzqm())))
				&& ((this.getQhdm() == castOther.getQhdm()) || (this.getQhdm() != null
						&& castOther.getQhdm() != null && this.getQhdm()
						.equals(castOther.getQhdm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result
				+ (getXzqm() == null ? 0 : this.getXzqm().hashCode());
		result = 37 * result
				+ (getQhdm() == null ? 0 : this.getQhdm().hashCode());
		return result;
	}

}
